title: <p align ="center">Rakesh Khanna </p>
logo: /assets/img/RAKESHKHANNA _ 00065648_ICardTwo1.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
